spring:
  application:
    name : blogbackend
  datasource:
    url : ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    contextPath: /api
jwt:
  secret-key:
    ${JWT_SECRET}
  expiration-time:
    ${JWT_EXPIRATION}
logging:
  level:
    org:
      springframework:
        security:
          DEBUG



